const listaDeProductos = [
  {
    nombre: "Molita",
    imagenUrl: "https://i.etsystatic.com/32986614/r/il/614716/3743811911/il_fullxfull.3743811911_dhrf.jpg",
    descripcion: "Bolso artesanal tejida por la comunidad Guna, usando fibras naturales y colores vibrantes.",
    precio: 35.0,
    comunidad: "Guna",
    categoria: "Artesanias",
    disponibilidad: true,
    descripcionCultura: "La cultura Guna es conocida por sus artesanías, en especial la creación de molas, que son piezas de tela colorida y tejida a mano. Su conexión con la naturaleza es una parte fundamental de su identidad.",
    imagenCultura: "https://www.worldwildlife.org/photos/guna-woman-making-mola",
  },
  {
    nombre: "Sombrero Pintao",
    imagenUrl: "https://embajadadepanamaenfrancia.fr/wp-content/uploads/2020/12/sombrero-pintao.jpg",
    descripcion: "Sombrero tradicional de fibra de caña, usado en celebraciones y danzas.",
    precio: 50.0,
    comunidad: "Embera",
    categoria: "Vestimenta",
    disponibilidad: true,
    descripcionCultura: "La cultura Embera es reconocida por su rica tradición artesanal y su profundo respeto por la naturaleza. Sus cestas tejidas y tatuajes temporales hechos con tinta de jagua son parte fundamental de su identidad cultural.",
    imagenCultura: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
  },
  {
    nombre: "Sombrero noPintao",
    imagenUrl: "https://embajadadepanamaenfrancia.fr/wp-content/uploads/2020/12/sombrero-pintao.jpg",
    descripcion: "Sombrero tradicional de fibra de caña, usado en celebraciones y danzas.",
    precio: 50.0,
    comunidad: "Embera",
    categoria: "Vestimenta",
    disponibilidad: true,
    descripcionCultura: "La cultura Embera es reconocida por su rica tradición artesanal y su profundo respeto por la naturaleza. Sus cestas tejidas y tatuajes temporales hechos con tinta de jagua son parte fundamental de su identidad cultural.",
    imagenCultura: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
  },
  {
    nombre: "Chaquira",
    imagenUrl: "https://tienda.cielo.org.mx/wp-content/uploads/2021/10/IMG_5753-2-scaled.jpg",
    descripcion: "Pulsera elaborada con cuentas de colores, típica de la comunidad Ngäbe-Buglé.",
    precio: 20.0,
    comunidad: "Ngäbe-Buglé",
    categoria: "Joyería",
    disponibilidad: false,
    descripcionCultura: "La comunidad Ngäbe-Buglé es conocida por sus vestidos tradicionales de colores brillantes y la elaboración de chaquiras, collares y pulseras hechos a mano, que son piezas fundamentales de su cultura.",
    imagenCultura: "https://i.pinimg.com/736x/28/f4/25/28f4257ddf8745b9ca6f3f802e80fcc8.jpg",
  },
  {
    nombre: "Chaquiras de Cuello",
    imagenUrl: "https://cdn.shopify.com/s/files/1/2393/9365/files/Captura_de_Pantalla_2022-04-04_a_la_s_11.37.46_480x480.png?v=1649090354",
    descripcion: "Collares tradicionales hechos a mano con cuentas pequeñas y patrones complejos.",
    precio: 30.0,
    comunidad: "Guna",
    categoria: "Joyería",
    disponibilidad: true,
    descripcionCultura: "La cultura Guna es conocida por sus artesanías, en especial la creación de molas, que son piezas de tela colorida y tejida a mano. Su conexión con la naturaleza es una parte fundamental de su identidad.",
    imagenCultura: "https://www.worldwildlife.org/photos/guna-woman-making-mola",
  },
  {
    nombre: "Nuchu",
    imagenUrl: "https://pbs.twimg.com/media/EdEGXiPWAAA6xU7.jpg",
    descripcion: "Figura tallada en madera que representa un espíritu protector, común en la cultura Guna.",
    precio: 45.0,
    comunidad: "Guna",
    categoria: "Escultura",
    disponibilidad: true,
    descripcionCultura: "La cultura Guna es conocida por sus artesanías, en especial la creación de molas, que son piezas de tela colorida y tejida a mano. Su conexión con la naturaleza es una parte fundamental de su identidad.",
    imagenCultura: "https://www.worldwildlife.org/photos/guna-woman-making-mola",
  },
  {
    nombre: "Balsería",
    imagenUrl: "https://www.panamaamerica.com.pa/sites/default/files/imagenes/2024/03/25/balseria-turismo-cultural.jpg",
    descripcion: "Juego tradicional indígena de lanzamiento de palos, promovido por la comunidad Ngäbe-Buglé.",
    precio: 100.0,
    comunidad: "Ngäbe-Buglé",
    categoria: "Juegos Tradicionales",
    disponibilidad: true,
    descripcionCultura: "La comunidad Ngäbe-Buglé es conocida por sus vestidos tradicionales de colores brillantes y la elaboración de chaquiras, collares y pulseras hechos a mano, que son piezas fundamentales de su cultura.",
    imagenCultura: "https://i.pinimg.com/736x/28/f4/25/28f4257ddf8745b9ca6f3f802e80fcc8.jpg",
  },
  {
    nombre: "Cesta Embera",
    imagenUrl: "https://lacabanga.com/wp-content/uploads/2022/07/cestaembera.jpg",
    descripcion: "Cesta tejida con fibras naturales, utilizada por la comunidad Embera para el transporte de alimentos.",
    precio: 60.0,
    comunidad: "Embera",
    categoria: "Artesanias",
    disponibilidad: false,
    descripcionCultura: "La cultura Embera es reconocida por su rica tradición artesanal y su profundo respeto por la naturaleza. Sus cestas tejidas y tatuajes temporales hechos con tinta de jagua son parte fundamental de su identidad cultural.",
    imagenCultura: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
  },
  {
    nombre: "Tatuaje",
    imagenUrl: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
    descripcion: "Tatuaje tradicional hecho a base de jagua, un tinte natural de la región.",
    precio: 15.0,
    comunidad: "Embera",
    categoria: "Arte Corporal",
    disponibilidad: true,
    descripcionCultura: "La cultura Embera es reconocida por su rica tradición artesanal y su profundo respeto por la naturaleza. Sus cestas tejidas y tatuajes temporales hechos con tinta de jagua son parte fundamental de su identidad cultural.",
    imagenCultura: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
  },
  {
    nombre: "Tatuaje Temporal Embera",
    imagenUrl: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
    descripcion: "Tatuaje tradicional hecho a base de jagua, un tinte natural de la región.",
    precio: 15.0,
    comunidad: "Embera",
    categoria: "Arte Corporal",
    disponibilidad: true,
    descripcionCultura: "La cultura Embera es reconocida por su rica tradición artesanal y su profundo respeto por la naturaleza. Sus cestas tejidas y tatuajes temporales hechos con tinta de jagua son parte fundamental de su identidad cultural.",
    imagenCultura: "https://ensegundos.com.pa/wp-content/uploads/2023/11/Los-grupos-etnicos-embera-wounaan.jpg",
  }
];

export default listaDeProductos;